### ISSUE TITLE
Flipped REF/ALT alleles

### ISSUE THREAD

**Issue by sarahgra** [dajiangliu/rareGWAMA#1]
I'm trying to do a conditional analysis using rvtests generated input files. In some studies for a given chromosome and position, the REF/ALT might be C/T while others may have it coded oppositely as REF/ALT T/C.  It seems that rareGWAMA treats these as two different variants rather than being equivalent (whereas RAREMETAL and METAL handle the flipping internally).  Is there any way of having rareGWAMA handle this internally rather than having to reformat the summary statistics files?

**Comment by dajiangliu** [comment]
Yes, for rareGWAMA, it mostly deals with imputation based GWAS, so I
assumed that the strand and ref/alt is correct. For rareMETALS, it was
developed for exome chip studies, where the allele labels are incorrect all
the time, so we have careful checks there (but it is slow) If the flip in
your study is not too many, would you please reformatted manually? I can
try to implement it as well to give user an option to check flips.

All the best,
Dajiang
--
Associate Professor
Dept. Public Health Sciences
Institute of Personalized Medicine
Penn State College of Medicine, HCAR 2020
Email: dajiang.liu@psu.edu
URL: https://dajiangliu.blog  <https://dajiangliu.blog>
Tel: +1-717-531-4178

**Comment by sarahgra** [comment]
Ok, I can probably reformat the study files then.  These are imputation-based studies but are a mix of 1000 genomes, HRC, and custom imputation panels so some studies have the effect alleles coded differently.

**Comment by dajiangliu** [comment]
Thank you! BTW, we always report alternative allele effects as default.

All the best,
Dajiang
--
Associate Professor
Dept. Public Health Sciences
Institute of Personalized Medicine
Penn State College of Medicine, HCAR 2020
Email: dajiang.liu@psu.edu
URL: https://dajiangliu.blog  <https://dajiangliu.blog>
Tel: +1-717-531-4178
